API_KEY = "此处填API密钥"
USE_PROXY = False
proxies = None
LLM_MODEL = "gpt-3.5-turbo"
AVAIL_LLM_MODELS = ["gpt-4-1106-preview", "gpt-4-turbo-preview", "gpt-4-vision-preview",
                    "gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-4-turbo-2024-04-09",
                    "gpt-3.5-turbo-1106", "gpt-3.5-turbo-16k", "gpt-3.5-turbo", "azure-gpt-3.5",
                    "gpt-4", "gpt-4-32k", "azure-gpt-4", "glm-4", "glm-4v", "glm-3-turbo",
                    "gemini-pro", "chatglm3"
                    ]
API_URL_REDIRECT = {}
DEFAULT_WORKER_NUM = 3
THEME = "Default"
AVAIL_THEMES = ['Default', 'Chuanhu-Small-and-Beautiful', 'High-Contrast', 'Gstaff/Xkcd', 'NoCrypt/Miku']
INIT_SYS_PROMPT = "Serve me as a writing and programming assistant."
CHATBOT_HEIGHT = 1115
CODE_HIGHLIGHT = True
LAYOUT = "LEFT-RIGHT"
DARK_MODE = True
TIMEOUT_SECONDS = 30
WEB_PORT = -1
AUTO_OPEN_BROWSER = True
MAX_RETRY = 2
DEFAULT_FN_GROUPS = ['对话', '编程', '学术', '智能体']
MULTI_QUERY_LLM_MODELS = "gpt-3.5-turbo&chatglm3"
QWEN_LOCAL_MODEL_SELECTION = "Qwen/Qwen-1_8B-Chat-Int8"
DASHSCOPE_API_KEY = ""
BAIDU_CLOUD_API_KEY = ""
BAIDU_CLOUD_SECRET_KEY = ""
BAIDU_CLOUD_QIANFAN_MODEL = "ERNIE-Bot"
CHATGLM_PTUNING_CHECKPOINT = ""
LOCAL_MODEL_DEVICE = "cpu"
LOCAL_MODEL_QUANT = "FP16"
SLACK_CLAUDE_BOT_ID = ""
SLACK_CLAUDE_USER_TOKEN = ""
AZURE_ENDPOINT = "https://你亲手写的api名称.openai.azure.com/"
AZURE_API_KEY = "填入azure openai api的密钥"
AZURE_ENGINE = "填入你亲手写的部署名"
AZURE_CFG_ARRAY = {}
ENABLE_AUDIO = False
ALIYUN_TOKEN = ""
ALIYUN_APPKEY = ""
ALIYUN_ACCESSKEY = ""
ALIYUN_SECRET = ""
TTS_TYPE = "DISABLE"
GPT_SOVITS_URL = ""
EDGE_TTS_VOICE = "zh-CN-XiaoxiaoNeural"
XFYUN_APPID = "00000000"
XFYUN_API_SECRET = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
XFYUN_API_KEY = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
ZHIPUAI_API_KEY = ""
ZHIPUAI_MODEL = ""
ANTHROPIC_API_KEY = ""
MOONSHOT_API_KEY = ""
YIMODEL_API_KEY = ""
MATHPIX_APPID = ""
MATHPIX_APPKEY = ""
DOC2X_API_KEY = ""
CUSTOM_API_KEY_PATTERN = ""
GEMINI_API_KEY = ""
CONCURRENT_COUNT = 100
AUTO_CLEAR_TXT = False
ADD_WAIFU = False
AUTHENTICATION = []
CUSTOM_PATH = "/"
SSL_KEYFILE = ""
SSL_CERTFILE = ""
API_ORG = ""
HUGGINGFACE_ACCESS_TOKEN = "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"
GROBID_URLS = ['']
ALLOW_RESET_CONFIG = False
AUTOGEN_USE_DOCKER = False
PATH_PRIVATE_UPLOAD = "private_upload"
PATH_LOGGING = "gpt_log"
WHEN_TO_USE_PROXY = ['']
BLOCK_INVALID_APIKEY = False
PLUGIN_HOT_RELOAD = False
NUM_CUSTOM_BASIC_BTN = 4
